/* Generated By:JavaCC: Do not edit this line. KarloffConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KarloffConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int NVAR = 6;
  /** RegularExpression Id. */
  int ACHAVES = 7;
  /** RegularExpression Id. */
  int FCHAVES = 8;
  /** RegularExpression Id. */
  int APAR = 9;
  /** RegularExpression Id. */
  int FPAR = 10;
  /** RegularExpression Id. */
  int PVIRG = 11;
  /** RegularExpression Id. */
  int VIRG = 12;
  /** RegularExpression Id. */
  int VOID = 13;
  /** RegularExpression Id. */
  int INT = 14;
  /** RegularExpression Id. */
  int BOOL = 15;
  /** RegularExpression Id. */
  int TRUE = 16;
  /** RegularExpression Id. */
  int FALSE = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int THEN = 19;
  /** RegularExpression Id. */
  int WHILE = 20;
  /** RegularExpression Id. */
  int REPEAT = 21;
  /** RegularExpression Id. */
  int RETURN = 22;
  /** RegularExpression Id. */
  int UNTIL = 23;
  /** RegularExpression Id. */
  int SOUPUT = 24;
  /** RegularExpression Id. */
  int ATRIB = 25;
  /** RegularExpression Id. */
  int FUNC = 26;
  /** RegularExpression Id. */
  int TOKEN_LITERAL = 27;
  /** RegularExpression Id. */
  int TOKEN_ID = 28;
  /** RegularExpression Id. */
  int NUM = 29;
  /** RegularExpression Id. */
  int OP = 30;
  /** RegularExpression Id. */
  int ID = 31;
  /** RegularExpression Id. */
  int DIGITO = 32;
  /** RegularExpression Id. */
  int LETRA = 33;
  /** RegularExpression Id. */
  int DIGITOS = 34;
  /** RegularExpression Id. */
  int LETRAOUDIGITO = 35;
  /** RegularExpression Id. */
  int FINALSUBLINHADO = 36;
  /** RegularExpression Id. */
  int EXPOENTE_OPCIONAL = 37;
  /** RegularExpression Id. */
  int FACAO_OPCIONAL = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"newVar\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "\"void\"",
    "\"int\"",
    "\"bool\"",
    "\"true\"",
    "\"false\"",
    "\"if\"",
    "\"then\"",
    "\"while\"",
    "\"repeat\"",
    "\"return\"",
    "\"until\"",
    "\"System.output\"",
    "\"=\"",
    "\"func\"",
    "<TOKEN_LITERAL>",
    "<TOKEN_ID>",
    "<NUM>",
    "<OP>",
    "<ID>",
    "<DIGITO>",
    "<LETRA>",
    "<DIGITOS>",
    "<LETRAOUDIGITO>",
    "<FINALSUBLINHADO>",
    "<EXPOENTE_OPCIONAL>",
    "<FACAO_OPCIONAL>",
  };

}
